# Generated by Django 3.2.9 on 2021-12-07 20:26

from django.db import migrations



def seed_database(apps, _):
    """ Seed the ball numbers into the database """
    balls = apps.get_model('play', 'Ball')
    combinations = apps.get_model('play', 'Combinations')
    dat = {
        "ambo": [0],
        "terno": [0],
        "quaterna":[0],
        "cinquina":[0],
        "tombola":[0],
    }
    combinations.objects.create(**dat)
    balls.objects.all().delete()
    for i in range(1, 91):
        data = {
            "num_value" : i,
            "is_played" : False
        }
        ball = balls.objects.create(**data)
        ball.save()


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_database)

            ]
