# Generated by Django 3.2.9 on 2021-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20211207_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=0),
            preserve_default=False,
        ),
    ]
