# Generated by Django 3.2.9 on 2021-12-16 21:37

from django.db import migrations

def seed_database(apps, _):
    """ Seed the ball numbers into the database """
    balls = apps.get_model('play', 'Ball')
    combinations = apps.get_model('play', 'Combinations')
    dat = {
        "ambo": [],
        "terno": [],
        "quaterna":[],
        "cinquina":[],
        "tombola":[],
    }
    combinations.objects.create(**dat)
    balls.objects.all().delete()
    for i in range(1, 91):
        data = {
            "num_value" : i,
            "is_played" : False
        }
        ball = balls.objects.create(**data)
        ball.save()


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_ball_updated_at'),
    ]

    operations = [
            migrations.RunPython(seed_database)

    ]
